import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "@/context/globalContext";
import Header from "@/app/component/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <GlobalProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F5F3F0]`}
        >
          <Header></Header>
          <main className="min-h-screen bg-[#C2B280] text-[#0F172A]  w-full">
            {children}
          </main>
        </body>
      </GlobalProvider>
    </html>
  );
}
